name: Flutter Test

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/flutter-test.yml"
      - "!**.md"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/flutter-test.yml"
      - "!**.md"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@master
        with:
          channel: "beta"
      - run: flutter pub get
      - run: flutter test
      - name: Slack Notification
        uses: lazy-actions/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*DecoratedAppBar test*'
          channel: '#dev'
          url: ${{ secrets.SLACK_WEBHOOK }}

